export const mockRecipes = [
  {
    id: "hf-001",
    name: "Creamy Tuscan Chicken",
    source: "HelloFresh",
    prepTime: 10,
    cookTime: 25,
    servings: 2,
    dietary: ["high-protein"],
    cuisine: "light",
    season: "all",
    overview: "Juicy chicken breast in a sun-dried tomato cream sauce with spinach over pasta.",
    keywords: ["chicken", "pasta", "creamy", "italian", "tuscan"],
    macros: { protein: 48, carbs: 52, fat: 22, calories: 590 },
    steps: [
      "Bring a pot of salted water to a boil. Cook pasta according to package instructions.",
      "Season chicken with salt and pepper. Heat oil in a skillet over medium-high heat.",
      "Cook chicken 5-6 minutes per side until cooked through. Remove and slice.",
      "In same pan, sauté garlic 30 seconds. Add sun-dried tomatoes and cream.",
      "Simmer 3 minutes, then stir in spinach until wilted.",
      "Add pasta and chicken back to pan. Toss to coat and serve."
    ],
    ingredients: [
      { name: "chicken breast", amount: "2 pieces (300g)" },
      { name: "pasta", amount: "180g" },
      { name: "heavy cream", amount: "120ml" },
      { name: "sun-dried tomatoes", amount: "60g" },
      { name: "baby spinach", amount: "80g" },
      { name: "garlic", amount: "3 cloves" },
      { name: "olive oil", amount: "2 tbsp" },
      { name: "parmesan", amount: "30g" }
    ]
  },
  {
    id: "hf-002",
    name: "Thai Green Curry with Tofu",
    source: "HelloFresh",
    prepTime: 15,
    cookTime: 20,
    servings: 2,
    dietary: ["vegetarian", "gluten-free"],
    cuisine: "light",
    season: "all",
    overview: "Fragrant green curry with crispy tofu, snap peas, and jasmine rice.",
    keywords: ["thai", "curry", "tofu", "vegetarian", "spicy"],
    macros: { protein: 22, carbs: 65, fat: 18, calories: 510 },
    steps: [
      "Press tofu dry and cut into cubes. Pan-fry until golden on all sides.",
      "Cook jasmine rice according to package instructions.",
      "In a wok, fry green curry paste in coconut oil for 1 minute.",
      "Pour in coconut milk and vegetable stock. Bring to a simmer.",
      "Add snap peas and tofu. Cook 5 minutes.",
      "Stir in fish sauce and lime juice. Serve over rice with fresh basil."
    ],
    ingredients: [
      { name: "firm tofu", amount: "250g" },
      { name: "jasmine rice", amount: "160g" },
      { name: "coconut milk", amount: "400ml" },
      { name: "green curry paste", amount: "2 tbsp" },
      { name: "snap peas", amount: "120g" },
      { name: "vegetable stock", amount: "100ml" },
      { name: "lime", amount: "1" },
      { name: "fresh basil", amount: "handful" }
    ]
  },
  {
    id: "hf-003",
    name: "Salmon with Lemon Dill Sauce",
    source: "HelloFresh",
    prepTime: 5,
    cookTime: 15,
    servings: 2,
    dietary: ["gluten-free", "high-protein"],
    cuisine: "light",
    season: "summer",
    overview: "Pan-seared salmon fillet with a bright lemon dill cream sauce and roasted asparagus.",
    keywords: ["salmon", "fish", "seafood", "lemon", "healthy"],
    macros: { protein: 44, carbs: 18, fat: 28, calories: 490 },
    steps: [
      "Preheat oven to 200°C. Toss asparagus with olive oil, salt, pepper.",
      "Roast asparagus 12 minutes until tender.",
      "Season salmon with salt and pepper. Sear skin-side down 4 minutes.",
      "Flip and cook 2 more minutes. Remove from pan.",
      "In same pan, combine cream, lemon zest, lemon juice, and dill.",
      "Simmer 2 minutes until slightly thickened. Serve over salmon."
    ],
    ingredients: [
      { name: "salmon fillet", amount: "2 pieces (320g)" },
      { name: "asparagus", amount: "200g" },
      { name: "heavy cream", amount: "80ml" },
      { name: "lemon", amount: "1" },
      { name: "fresh dill", amount: "15g" },
      { name: "butter", amount: "20g" },
      { name: "olive oil", amount: "1 tbsp" }
    ]
  },
  {
    id: "ms-001",
    name: "Dutch Stamppot with Smoked Sausage",
    source: "Marley Spoon",
    prepTime: 10,
    cookTime: 30,
    servings: 2,
    dietary: ["traditional"],
    cuisine: "dutch",
    season: "winter",
    overview: "Classic Dutch mashed potato and kale dish served with smoky rookworst sausage.",
    keywords: ["dutch", "stamppot", "sausage", "comfort food", "winter"],
    macros: { protein: 32, carbs: 72, fat: 26, calories: 640 },
    steps: [
      "Boil potatoes in salted water until tender, about 20 minutes.",
      "Meanwhile, cook rookworst in simmering water for 15 minutes.",
      "Steam or blanch kale for 3 minutes until wilted.",
      "Drain potatoes and mash with butter and warm milk.",
      "Fold kale through the mash. Season generously with salt and pepper.",
      "Serve stamppot with sliced sausage and a dollop of mustard."
    ],
    ingredients: [
      { name: "floury potatoes", amount: "600g" },
      { name: "rookworst sausage", amount: "250g" },
      { name: "curly kale", amount: "200g" },
      { name: "butter", amount: "50g" },
      { name: "whole milk", amount: "80ml" },
      { name: "Dutch mustard", amount: "2 tbsp" }
    ]
  },
  {
    id: "ms-002",
    name: "Pea Soup (Erwtensoep)",
    source: "Marley Spoon",
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    dietary: ["traditional"],
    cuisine: "dutch",
    season: "winter",
    overview: "Thick, hearty Dutch split pea soup with smoked pork and celeriac.",
    keywords: ["dutch", "soup", "pea", "erwtensoep", "traditional"],
    macros: { protein: 28, carbs: 58, fat: 14, calories: 470 },
    steps: [
      "Rinse split peas and place in large pot with water and pork.",
      "Bring to boil, skim foam, then simmer 30 minutes.",
      "Add diced celeriac, leek, carrot, and celery.",
      "Cook another 15 minutes until vegetables are tender.",
      "Remove pork, shred meat, and return to pot.",
      "Season with salt and pepper. Serve thick with rye bread."
    ],
    ingredients: [
      { name: "green split peas", amount: "400g" },
      { name: "smoked pork shoulder", amount: "300g" },
      { name: "celeriac", amount: "200g" },
      { name: "leek", amount: "2 stalks" },
      { name: "carrot", amount: "2" },
      { name: "celery", amount: "3 stalks" },
      { name: "bay leaves", amount: "2" }
    ]
  },
  {
    id: "ms-003",
    name: "Grilled Zucchini & Feta Salad",
    source: "Marley Spoon",
    prepTime: 10,
    cookTime: 10,
    servings: 2,
    dietary: ["vegetarian", "gluten-free"],
    cuisine: "light",
    season: "summer",
    overview: "Charred zucchini ribbons with creamy feta, mint, and a lemon-herb dressing.",
    keywords: ["salad", "zucchini", "feta", "vegetarian", "summer"],
    macros: { protein: 14, carbs: 18, fat: 24, calories: 330 },
    steps: [
      "Slice zucchini lengthwise into thin ribbons.",
      "Brush with olive oil and grill on high heat 2 minutes per side.",
      "Whisk together olive oil, lemon juice, garlic, and oregano.",
      "Arrange grilled zucchini on plate. Crumble feta over top.",
      "Scatter fresh mint and drizzle with dressing.",
      "Finish with pine nuts and a pinch of chili flakes."
    ],
    ingredients: [
      { name: "zucchini", amount: "3 medium" },
      { name: "feta cheese", amount: "120g" },
      { name: "fresh mint", amount: "20g" },
      { name: "lemon", amount: "1" },
      { name: "pine nuts", amount: "30g" },
      { name: "olive oil", amount: "3 tbsp" },
      { name: "garlic", amount: "1 clove" }
    ]
  },
  {
    id: "nyt-001",
    name: "Shakshuka with Feta",
    source: "NYT Cooking",
    prepTime: 5,
    cookTime: 20,
    servings: 2,
    dietary: ["vegetarian", "gluten-free"],
    cuisine: "light",
    season: "all",
    overview: "Eggs poached in a spiced tomato-pepper sauce, topped with creamy feta and herbs.",
    keywords: ["eggs", "tomato", "shakshuka", "vegetarian", "breakfast"],
    macros: { protein: 20, carbs: 22, fat: 18, calories: 320 },
    steps: [
      "Heat olive oil in an oven-safe skillet. Sauté onion and pepper 8 minutes.",
      "Add garlic, cumin, paprika, and chili flakes. Cook 1 minute.",
      "Pour in crushed tomatoes. Season and simmer 10 minutes.",
      "Make 4 wells in the sauce. Crack eggs into each well.",
      "Cover and cook on low until whites are set, 8-10 minutes.",
      "Crumble feta over top. Garnish with parsley and serve with crusty bread."
    ],
    ingredients: [
      { name: "eggs", amount: "4 large" },
      { name: "crushed tomatoes", amount: "400g can" },
      { name: "feta cheese", amount: "80g" },
      { name: "red bell pepper", amount: "1" },
      { name: "onion", amount: "1 medium" },
      { name: "garlic", amount: "3 cloves" },
      { name: "cumin", amount: "1 tsp" },
      { name: "smoked paprika", amount: "1 tsp" },
      { name: "fresh parsley", amount: "handful" }
    ]
  },
  {
    id: "nyt-002",
    name: "Sheet Pan Lemon Chicken & Vegetables",
    source: "NYT Cooking",
    prepTime: 10,
    cookTime: 40,
    servings: 4,
    dietary: ["gluten-free", "high-protein"],
    cuisine: "light",
    season: "all",
    overview: "One-pan roasted chicken thighs with seasonal vegetables and bright lemon-herb marinade.",
    keywords: ["chicken", "sheet pan", "roasted", "vegetables", "easy"],
    macros: { protein: 42, carbs: 28, fat: 24, calories: 490 },
    steps: [
      "Preheat oven to 220°C. Combine olive oil, lemon juice, garlic, thyme, and rosemary.",
      "Toss chicken thighs in marinade. Arrange on sheet pan.",
      "Surround chicken with potatoes, cherry tomatoes, and olives.",
      "Season everything with salt and pepper.",
      "Roast 35-40 minutes until chicken is golden and cooked through.",
      "Rest 5 minutes before serving. Spoon pan juices over everything."
    ],
    ingredients: [
      { name: "chicken thighs", amount: "4 pieces (800g)" },
      { name: "baby potatoes", amount: "400g" },
      { name: "cherry tomatoes", amount: "200g" },
      { name: "kalamata olives", amount: "80g" },
      { name: "lemon", amount: "2" },
      { name: "garlic", amount: "4 cloves" },
      { name: "fresh thyme", amount: "4 sprigs" },
      { name: "fresh rosemary", amount: "2 sprigs" },
      { name: "olive oil", amount: "3 tbsp" }
    ]
  },
  {
    id: "nyt-003",
    name: "Black Bean Tacos with Mango Salsa",
    source: "NYT Cooking",
    prepTime: 15,
    cookTime: 10,
    servings: 2,
    dietary: ["vegetarian", "gluten-free"],
    cuisine: "light",
    season: "summer",
    overview: "Crispy black bean tacos with sweet mango salsa, avocado, and a lime crema.",
    keywords: ["tacos", "black bean", "vegetarian", "mango", "mexican"],
    macros: { protein: 18, carbs: 68, fat: 20, calories: 520 },
    steps: [
      "Dice mango, red onion, jalapeño, and cilantro. Toss with lime juice for salsa.",
      "Heat black beans with cumin, chili powder, garlic powder, and salt.",
      "Warm tortillas directly over flame or in dry pan.",
      "Mash avocado with lime juice, salt, and garlic.",
      "Mix sour cream with lime juice and zest for crema.",
      "Assemble tacos: beans, avocado mash, mango salsa, drizzle of crema."
    ],
    ingredients: [
      { name: "black beans", amount: "400g can" },
      { name: "corn tortillas", amount: "6" },
      { name: "mango", amount: "1 large" },
      { name: "avocado", amount: "2" },
      { name: "sour cream", amount: "60ml" },
      { name: "jalapeño", amount: "1" },
      { name: "red onion", amount: "0.5" },
      { name: "cilantro", amount: "handful" },
      { name: "lime", amount: "2" }
    ]
  },
  {
    id: "hf-004",
    name: "Beef Bolognese",
    source: "HelloFresh",
    prepTime: 10,
    cookTime: 30,
    servings: 2,
    dietary: ["traditional", "high-protein"],
    cuisine: "light",
    season: "all",
    overview: "Rich slow-cooked beef ragù with spaghetti and fresh parmesan.",
    keywords: ["beef", "pasta", "bolognese", "italian", "classic"],
    macros: { protein: 45, carbs: 68, fat: 28, calories: 700 },
    steps: [
      "Finely chop onion, carrot, and celery.",
      "Brown beef mince in olive oil over high heat. Set aside.",
      "Soften vegetables 5 minutes. Add garlic and tomato paste.",
      "Return beef to pan. Pour in crushed tomatoes and red wine.",
      "Simmer 20 minutes until thick and rich. Season well.",
      "Cook spaghetti al dente. Serve topped with bolognese and parmesan."
    ],
    ingredients: [
      { name: "beef mince", amount: "300g" },
      { name: "spaghetti", amount: "180g" },
      { name: "crushed tomatoes", amount: "400g can" },
      { name: "onion", amount: "1" },
      { name: "carrot", amount: "1" },
      { name: "celery", amount: "2 stalks" },
      { name: "garlic", amount: "3 cloves" },
      { name: "tomato paste", amount: "2 tbsp" },
      { name: "red wine", amount: "100ml" },
      { name: "parmesan", amount: "40g" }
    ]
  },
  {
    id: "ms-004",
    name: "Spring Pea & Mint Risotto",
    source: "Marley Spoon",
    prepTime: 10,
    cookTime: 30,
    servings: 2,
    dietary: ["vegetarian"],
    cuisine: "light",
    season: "spring",
    overview: "Creamy arborio risotto with sweet spring peas, fresh mint, and lemon.",
    keywords: ["risotto", "pea", "vegetarian", "spring", "italian"],
    macros: { protein: 18, carbs: 75, fat: 20, calories: 550 },
    steps: [
      "Heat vegetable stock in a saucepan. Keep warm on low.",
      "Sauté shallot and garlic in butter until soft, 4 minutes.",
      "Add arborio rice and toast 2 minutes. Add white wine.",
      "Add stock one ladle at a time, stirring constantly, 18-20 minutes.",
      "Stir in peas in last 3 minutes of cooking.",
      "Remove from heat. Stir in butter, parmesan, mint, and lemon zest. Season."
    ],
    ingredients: [
      { name: "arborio rice", amount: "200g" },
      { name: "frozen peas", amount: "150g" },
      { name: "vegetable stock", amount: "900ml" },
      { name: "shallot", amount: "2" },
      { name: "white wine", amount: "100ml" },
      { name: "butter", amount: "40g" },
      { name: "parmesan", amount: "50g" },
      { name: "fresh mint", amount: "15g" },
      { name: "lemon", amount: "1" }
    ]
  },
  {
    id: "nyt-004",
    name: "Roasted Butternut Squash Soup",
    source: "NYT Cooking",
    prepTime: 15,
    cookTime: 45,
    servings: 4,
    dietary: ["vegetarian", "gluten-free"],
    cuisine: "light",
    season: "autumn",
    overview: "Silky roasted butternut squash soup with warming spices and toasted pepitas.",
    keywords: ["soup", "squash", "autumn", "vegetarian", "warming"],
    macros: { protein: 8, carbs: 42, fat: 14, calories: 320 },
    steps: [
      "Preheat oven to 200°C. Halve squash, brush with oil, roast cut-side down 40 min.",
      "Scoop squash flesh into blender.",
      "Sauté onion and garlic in butter. Add to blender.",
      "Add vegetable stock, ginger, cinnamon, and nutmeg.",
      "Blend until completely smooth. Return to pot and heat through.",
      "Season well. Serve with a swirl of cream and toasted pepitas."
    ],
    ingredients: [
      { name: "butternut squash", amount: "1kg" },
      { name: "vegetable stock", amount: "700ml" },
      { name: "onion", amount: "1 large" },
      { name: "garlic", amount: "3 cloves" },
      { name: "fresh ginger", amount: "1 tsp" },
      { name: "butter", amount: "30g" },
      { name: "heavy cream", amount: "60ml" },
      { name: "pepitas", amount: "30g" }
    ]
  }
];
